<?php
$menus= array();
$menus[0]['title']= 'Netloading';
$menus[0]['sub'][0]= array('name'=>'Danh sách người dùng','classIcon'=>'glyphicon glyphicon-bed','url'=>$urlPlugins.'admin/netLoading-admin-listCustomer.php');

addMenuAdminMantan($menus);

function getListTypeCar()
{
	/* 
	group 1: Hàng khô
	group 2: Hàng lạnh
	group 3: Hàng lỏng
	group 4: Hàng khoáng sản
	group 5: Hàng khác
	*/
	return array('1'=>array('id'=>1,'name'=>'Xe tải','group'=>1),
				'2'=>array('id'=>2,'name'=>'Xe đầu kéo','group'=>1),
				'3'=>array('id'=>3,'name'=>'Xe container','group'=>1),
				'4'=>array('id'=>4,'name'=>'Xe đông lạnh','group'=>2),
				'5'=>array('id'=>5,'name'=>'Xe bồn','group'=>3),
				'6'=>array('id'=>6,'name'=>'Xe ben','group'=>4),
				'7'=>array('id'=>7,'name'=>'Xe cẩu','group'=>5),
				'8'=>array('id'=>8,'name'=>'Xe chuyên dụng khác','group'=>5),
				
		);
}

function getTypeWeight()
{
	return array('1'=>array('id'=>1,'name'=>'kg','proportion'=>1),
				'2'=>array('id'=>2,'name'=>'tấn','proportion'=>1000)
		);
}

function getTypeVolume()
{
	return array('1'=>array('id'=>1,'name'=>'m³','proportion'=>1),
				
		);
}

function getTypeMoney()
{
	return array('1'=>array('id'=>1,'name'=>'VND','proportion'=>1),
						);
}

function getListCity()
{
	return array(	'1'=>array('id'=>1,'name'=>'An Giang','gps'=>'10.503183,105.119829'),
					'2'=>array('id'=>2,'name'=>'Bà Rịa - Vũng Tàu','gps'=>'10.563561,107.276515'),
					'3'=>array('id'=>3,'name'=>'Bắc Giang','gps'=>'21.362262,106.176664'),
					'4'=>array('id'=>4,'name'=>'Bắc Kạn','gps'=>'22.240912,105.819391'),
					'5'=>array('id'=>5,'name'=>'Bạc Liêu','gps'=>'9.291818,105.467610'),
					'6'=>array('id'=>6,'name'=>'Bắc Ninh','gps'=>'21.136271,106.083659'),
					'7'=>array('id'=>7,'name'=>'Bến Tre','gps'=>'10.137806,106.565089'),
					'8'=>array('id'=>8,'name'=>'Bình Định','gps'=>'14.169255,108.899803'),
					'9'=>array('id'=>9,'name'=>'Bình Dương','gps'=>'11.207645,106.578304'),
					'10'=>array('id'=>10,'name'=>'Bình Phước','gps'=>'11.680601,106.825329'),
					'11'=>array('id'=>11,'name'=>'Bình Thuận','gps'=>'10.947979,107.826546'),
					'12'=>array('id'=>12,'name'=>'Cà Mau','gps'=>'8.820449,105.084218'),
					'13'=>array('id'=>13,'name'=>'Cao Bằng','gps'=>'22.803639,105.711757'),
					'14'=>array('id'=>14,'name'=>'Đắk Lắk','gps'=>'12.865012,108.003386'),
					'15'=>array('id'=>15,'name'=>'Đắk Nông','gps'=>'12.107715,107.830821'),
					'16'=>array('id'=>16,'name'=>'Điện Biên','gps'=>'21.752904,103.101496'),
					'17'=>array('id'=>17,'name'=>'Đồng Nai','gps'=>'10.714318,107.005192'),
					'18'=>array('id'=>18,'name'=>'Đồng Tháp','gps'=>'10.581382,105.688341'),
					'19'=>array('id'=>19,'name'=>'Gia Lai','gps'=>'13.870961,108.282026'),
					'20'=>array('id'=>20,'name'=>'Hà Giang','gps'=>'22.522165,104.765151'),
					'21'=>array('id'=>21,'name'=>'Hà Nam','gps'=>'20.447984,105.919875'),
					'22'=>array('id'=>22,'name'=>'Hà Tĩnh','gps'=>'18.264984,105.696628'),
					'23'=>array('id'=>23,'name'=>'Hải Dương','gps'=>'20.781788,106.289502'),
					'24'=>array('id'=>24,'name'=>'Hậu Giang','gps'=>'9.790570,105.576663'),
					'25'=>array('id'=>25,'name'=>'Hòa Bình','gps'=>'20.730707,105.474031'),
					'26'=>array('id'=>26,'name'=>'Hưng Yên','gps'=>'20.833808,106.010205'),
					'27'=>array('id'=>27,'name'=>'Khánh Hòa','gps'=>'12.307491,108.871089'),
					'28'=>array('id'=>28,'name'=>'Kiên Giang','gps'=>'10.009664,105.197401'),
					'29'=>array('id'=>29,'name'=>'Kon Tum','gps'=>'14.313554,107.920630'),
					'30'=>array('id'=>30,'name'=>'Lai Châu','gps'=>'22.324320,102.843735'),
					'31'=>array('id'=>31,'name'=>'Lâm Đồng','gps'=>'11.641015,107.497746'),
					'32'=>array('id'=>32,'name'=>'Lạng Sơn','gps'=>'21.820741,106.547897'),
					'33'=>array('id'=>33,'name'=>'Lào Cai','gps'=>'22.513893,103.856868'),
					'34'=>array('id'=>34,'name'=>'Long An','gps'=>'10.695005,105.960820'),
					'35'=>array('id'=>35,'name'=>'Nam Định','gps'=>'20.413892,106.162605'),
					'36'=>array('id'=>36,'name'=>'Nghệ An','gps'=>'19.395257,104.889498'),
					'37'=>array('id'=>37,'name'=>'Ninh Bình','gps'=>'20.247371,105.970816'),
					'38'=>array('id'=>38,'name'=>'Ninh Thuận','gps'=>'11.708233,108.886415'),
					'39'=>array('id'=>39,'name'=>'Phú Thọ','gps'=>'21.307744,105.125561'),
					'40'=>array('id'=>40,'name'=>'Quảng Bình','gps'=>'17.650996,106.225225'),
					'41'=>array('id'=>41,'name'=>'Quảng Nam','gps'=>'15.582603,107.985250'),
					'42'=>array('id'=>42,'name'=>'Quảng Ngãi','gps'=>'15.033132,108.631560'),
					'43'=>array('id'=>43,'name'=>'Quảng Ninh','gps'=>'21.151562,107.203928'),
					'44'=>array('id'=>44,'name'=>'Quảng Trị','gps'=>'16.725876,107.103291'),
					'45'=>array('id'=>45,'name'=>'Sóc Trăng','gps'=>'9.605473,105.973519'),
					'46'=>array('id'=>46,'name'=>'Sơn La','gps'=>'9.600734,105.978154'),
					'47'=>array('id'=>47,'name'=>'Tây Ninh','gps'=>'11.357658,106.130780'),
					'48'=>array('id'=>48,'name'=>'Thái Bình','gps'=>'20.506917,106.374343'),
					'49'=>array('id'=>49,'name'=>'Thái Nguyên','gps'=>'21.587135,105.824038'),
					'50'=>array('id'=>50,'name'=>'Thanh Hóa','gps'=>'20.091208,105.301704'),
					'51'=>array('id'=>51,'name'=>'Thừa Thiên Huế','gps'=>'16.344361,107.581729'),
					'52'=>array('id'=>52,'name'=>'Tiền Giang','gps'=>'10.438860,106.253686'),
					'53'=>array('id'=>53,'name'=>'Trà Vinh','gps'=>'9.934929,106.336861'),
					'54'=>array('id'=>54,'name'=>'Tuyên Quang','gps'=>'22.058060,105.244858'),
					'55'=>array('id'=>55,'name'=>'Vĩnh Long','gps'=>'10.244966,105.958561'),
					'56'=>array('id'=>56,'name'=>'Vĩnh Phúc','gps'=>'21.301371,105.591167'),
					'57'=>array('id'=>57,'name'=>'Yên Bái','gps'=>'21.718615,104.929472'),
					'58'=>array('id'=>58,'name'=>'Phú Yên','gps'=>'13.096341,109.292911'),
					'59'=>array('id'=>59,'name'=>'Cần Thơ','gps'=>'10.044264,105.748773'),
					'60'=>array('id'=>60,'name'=>'Đà Nẵng','gps'=>'16.053866,108.203836'),
					'61'=>array('id'=>61,'name'=>'Hải Phòng','gps'=>'20.843685,106.694454'),
					'62'=>array('id'=>62,'name'=>'Hà Nội','gps'=>'21.025905,105.846576'),
					'63'=>array('id'=>63,'name'=>'TP Hồ Chí Minh','gps'=>'10.820645,106.632518'),

		);
}

function getListDistrict($idCity='')
{
	$list   = array(            '1'=>array(      
                                                        '1'=>array('id'=>1,'name'=>'An Phú'),
							'2'=>array('id'=>2,'name'=>'Châu Đốc'),
							'3'=>array('id'=>3,'name'=>'Châu Phú'),
							'4'=>array('id'=>4,'name'=>'Châu Thành'),
							'5'=>array('id'=>5,'name'=>'Chợ Mới'),
							'6'=>array('id'=>6,'name'=>'Long Xuyên'),
							'7'=>array('id'=>7,'name'=>'Phú Tân'),
							'8'=>array('id'=>8,'name'=>'Tân Châu'),
							'9'=>array('id'=>9,'name'=>'Thoại Sơn'),
							'10'=>array('id'=>10,'name'=>'Tịnh Biên'),
							'11'=>array('id'=>11,'name'=>'Tri Tôn'),
						),
				'2'=>array(	
                                                        '1'=>array('id'=>1,'name'=>'Bà Rịa'),
							'2'=>array('id'=>2,'name'=>'Côn Đảo'),
							'3'=>array('id'=>3,'name'=>'Châu Đức'),
							'4'=>array('id'=>4,'name'=>'Đất Đỏ'),
							'5'=>array('id'=>5,'name'=>'Long Điền'),
							'6'=>array('id'=>6,'name'=>'Tân Thành'),
							'7'=>array('id'=>7,'name'=>'Vũng Tàu'),
							'8'=>array('id'=>8,'name'=>'Xuyên Mộc'),

						),
				'3'=>array(   
							'1'=>array('id'=>1,'name'=>'Bắc Giang'),
							'2'=>array('id'=>2,'name'=>'Hiệp Hòa'),
							'3'=>array('id'=>3,'name'=>'Lạng Giang'),
							'4'=>array('id'=>4,'name'=>'Lục Nam'),
							'5'=>array('id'=>5,'name'=>'Lục Ngạn'),
							'6'=>array('id'=>6,'name'=>'Sơn Động'),
							'7'=>array('id'=>7,'name'=>'Tân Yên'),
							'8'=>array('id'=>8,'name'=>'Việt Yên'),
							'9'=>array('id'=>9,'name'=>'Yên Dũng'),
							'10'=>array('id'=>10,'name'=>'Yên Thế'),
							),
				'4'=>array(   
							'1'=>array('id'=>1,'name'=>'Ba Bể'),
							'2'=>array('id'=>2,'name'=>'Bắc Kạn'),
							'3'=>array('id'=>3,'name'=>'Bạch Thông'),
							'4'=>array('id'=>4,'name'=>'Chợ Đồn'),
							'5'=>array('id'=>5,'name'=>'Chợ Mới'),
							'6'=>array('id'=>6,'name'=>'Na Rì'),
							'7'=>array('id'=>7,'name'=>'Ngân Sơn'),
							'8'=>array('id'=>8,'name'=>'Pác Nặm'),
							),

				'5'=>array(   
							'1'=>array('id'=>1,'name'=>'Bạc Liêu'),
							'2'=>array('id'=>2,'name'=>'Đông Hải'),
							'3'=>array('id'=>3,'name'=>'Giá Rai'),
							'4'=>array('id'=>4,'name'=>'Hoà Bình'),
							'5'=>array('id'=>5,'name'=>'Hồng Dân'),
							'6'=>array('id'=>6,'name'=>'Phước Long'),
							'7'=>array('id'=>7,'name'=>'Vĩnh Lợi'),
							),

				'6'=>array(   
							'1'=>array('id'=>1,'name'=>'Bắc Ninh'),
							'2'=>array('id'=>2,'name'=>'Gia Bình'),
							'3'=>array('id'=>3,'name'=>'Lương Tài'),
							'4'=>array('id'=>4,'name'=>'Quế Võ'),
							'5'=>array('id'=>5,'name'=>'Thuận Thành'),
							'6'=>array('id'=>6,'name'=>'Tiên Du'),
							'7'=>array('id'=>7,'name'=>'Từ Sơn'),
							'8'=>array('id'=>8,'name'=>'Yên Phong'),
							),
							
				'7'=>array(   
							'1'=>array('id'=>1,'name'=>'Ba Tri'),
							'2'=>array('id'=>2,'name'=>'Bến Tre'),
							'3'=>array('id'=>3,'name'=>'Bình Đại'),
							'4'=>array('id'=>4,'name'=>'Chợ Lách'),
							'5'=>array('id'=>5,'name'=>'Giồng Trôm'),
							'6'=>array('id'=>6,'name'=>'Mỏ Cày Bắc'),
							'7'=>array('id'=>7,'name'=>'Mỏ Cày Nam'),
							'8'=>array('id'=>8,'name'=>'Thạnh Phú'),
							),

				'8'=>array(   
							'1'=>array('id'=>1,'name'=>'An Nhơn'),
							'2'=>array('id'=>2,'name'=>'Hoài Ân'),
							'3'=>array('id'=>3,'name'=>'Hoài Nhơn'),
							'4'=>array('id'=>4,'name'=>'Phù Cát'),
							'5'=>array('id'=>5,'name'=>'Phù Mỹ'),
							'6'=>array('id'=>6,'name'=>'Qui Nhơn'),
							'7'=>array('id'=>7,'name'=>'Tây Sơn'),
							'8'=>array('id'=>8,'name'=>'Tuy Phước'),
							'9'=>array('id'=>9,'name'=>'Vân Canh'),
							'10'=>array('id'=>10,'name'=>'Vĩnh Thạnh'),
						),

				'9'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Tân Uyên'),
							'2'=>array('id'=>2,'name'=>'Bàu Bàng'),
							'3'=>array('id'=>3,'name'=>'Bến Cát'),
							'4'=>array('id'=>4,'name'=>'Dầu Tiếng'),
							'5'=>array('id'=>5,'name'=>'Dĩ An'),
							'6'=>array('id'=>6,'name'=>'Phú Giáo'),
							'7'=>array('id'=>7,'name'=>'Tân Uyên'),
							'8'=>array('id'=>8,'name'=>'Thủ Dầu Một'),
							'9'=>array('id'=>9,'name'=>'Thuận An'),   ),
				'10'=>array(  '1'=>array('id'=>1,'name'=>'Bình Long'),
							'2'=>array('id'=>2,'name'=>'Bù Đăng'),
							'3'=>array('id'=>3,'name'=>'Bù Đốp'),
							'4'=>array('id'=>4,'name'=>'Bù Gia Mập'),
							'5'=>array('id'=>5,'name'=>'Chơn Thành'),
							'6'=>array('id'=>6,'name'=>'Đồng Phú'),
							'7'=>array('id'=>7,'name'=>'Đồng Xoài'),
							'8'=>array('id'=>8,'name'=>'Hớn Quản'),
							'9'=>array('id'=>9,'name'=>'Lộc Ninh'),
							'10'=>array('id'=>10,'name'=>'Phú Riềng'),
							'11'=>array('id'=>11,'name'=>'Phước Long'),   ),
				'11'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Bình'),
							'2'=>array('id'=>2,'name'=>'Đức Linh'),
							'3'=>array('id'=>3,'name'=>'Hàm Tân'),
							'4'=>array('id'=>4,'name'=>'Hàm Thuận Bắc'),
							'5'=>array('id'=>5,'name'=>'Hàm Thuận Nam'),
							'6'=>array('id'=>6,'name'=>'La Gi'),
							'7'=>array('id'=>7,'name'=>'Phan Thiết'),
							'8'=>array('id'=>8,'name'=>'Phú Quí'),
							'9'=>array('id'=>9,'name'=>'Tánh Linh'),
							'10'=>array('id'=>10,'name'=>'Tuy Phong'),   ),
				'12'=>array(  '1'=>array('id'=>1,'name'=>'Cà Mau'),
							'2'=>array('id'=>2,'name'=>'Cái Nước'),
							'3'=>array('id'=>3,'name'=>'Đầm Dơi'),
							'4'=>array('id'=>4,'name'=>'Năm Căn'),
							'5'=>array('id'=>5,'name'=>'Ngọc Hiển'),
							'6'=>array('id'=>6,'name'=>'Thới Bình'),
							'7'=>array('id'=>7,'name'=>'U Minh'),
							'8'=>array('id'=>8,'name'=>'Văn Thời'),   ),
				'13'=>array(  '1'=>array('id'=>1,'name'=>'Bảo Lạc'),
							'2'=>array('id'=>2,'name'=>'Bảo Lâm'),
							'3'=>array('id'=>3,'name'=>'Cao Bằng'),
							'4'=>array('id'=>4,'name'=>'Hạ Lang'),
							'5'=>array('id'=>5,'name'=>'Hà Quảng'),
							'6'=>array('id'=>6,'name'=>'Hoà An'),
							'7'=>array('id'=>7,'name'=>'Nguyên Bình'),
							'8'=>array('id'=>8,'name'=>'Phục Hoà'),
							'9'=>array('id'=>9,'name'=>'Quảng Uyên'),
							'10'=>array('id'=>10,'name'=>'Thạch An'),
							'11'=>array('id'=>11,'name'=>'Thông Nông'),
							'12'=>array('id'=>12,'name'=>'Trà Lĩnh'),
							'13'=>array('id'=>13,'name'=>'Trùng Khánh'),   ),
				'14'=>array(  '1'=>array('id'=>1,'name'=>'Buôn Đôn'),
							'2'=>array('id'=>2,'name'=>'Buôn Hồ'),
							'3'=>array('id'=>3,'name'=>'Buôn Ma Thuột'),
							'4'=>array('id'=>4,'name'=>'Cư Kuin'),
							'5'=>array('id'=>5,'name'=>'Cư M"gar'),
							'6'=>array('id'=>6,'name'=>'Ea H"leo'),
							'7'=>array('id'=>7,'name'=>'Ea Kar'),
							'8'=>array('id'=>8,'name'=>'Ea Súp'),
							'9'=>array('id'=>9,'name'=>'Huyện Lắk'),
							'10'=>array('id'=>10,'name'=>'Krông A Na'),
							'11'=>array('id'=>11,'name'=>'Krông Bông'),
							'12'=>array('id'=>12,'name'=>'Krông Búk'),
							'13'=>array('id'=>13,'name'=>'Krông Năng'),
							'14'=>array('id'=>14,'name'=>'Krông Pắc'),
							'15'=>array('id'=>15,'name'=>'M"Đrắk'),   ),
				'15'=>array(  '1'=>array('id'=>1,'name'=>'Cư Jút'),
							'2'=>array('id'=>2,'name'=>'Đăk Glong'),
							'3'=>array('id'=>3,'name'=>'Đắk Mil'),
							'4'=>array('id'=>4,'name'=>'Đắk R"Lấp'),
							'5'=>array('id'=>5,'name'=>'Đắk Song'),
							'6'=>array('id'=>6,'name'=>'Gia Nghĩa'),
							'7'=>array('id'=>7,'name'=>'Krông Nô'),
							'8'=>array('id'=>8,'name'=>'Tuy Đức'),   ),
				'16'=>array(  '1'=>array('id'=>1,'name'=>'Điện Biên'),
							'2'=>array('id'=>2,'name'=>'Điện Biên Đông'),
							'3'=>array('id'=>3,'name'=>'Điện Biên Phủ'),
							'4'=>array('id'=>4,'name'=>'Mường Ảng'),
							'5'=>array('id'=>5,'name'=>'Mường Chà'),
							'6'=>array('id'=>6,'name'=>'Mường Lay'),
							'7'=>array('id'=>7,'name'=>'Mường Nhé'),
							'8'=>array('id'=>8,'name'=>'Nậm Pồ'),
							'9'=>array('id'=>9,'name'=>'Tủa Chùa'),
							'10'=>array('id'=>10,'name'=>'Tuần Giáo'),   ),
				'17'=>array(  '1'=>array('id'=>1,'name'=>'Biên Hòa'),
							'2'=>array('id'=>2,'name'=>'Cẩm Mỹ'),
							'3'=>array('id'=>3,'name'=>'Định Quán'),
							'4'=>array('id'=>4,'name'=>'Long Khánh'),
							'5'=>array('id'=>5,'name'=>'Long Thành'),
							'6'=>array('id'=>6,'name'=>'Nhơn Trạch'),
							'7'=>array('id'=>7,'name'=>'Tân Phú'),
							'8'=>array('id'=>8,'name'=>'Thống Nhất'),
							'9'=>array('id'=>9,'name'=>'Trảng Bom'),
							'10'=>array('id'=>10,'name'=>'Vĩnh Cửu'),
							'11'=>array('id'=>11,'name'=>'Xuân Lộc'),   ),
				'18'=>array('1'=>array('id'=>1,'name'=>'Cao Lãnh'),
							'2'=>array('id'=>2,'name'=>'Cao Lãnh'),
							'3'=>array('id'=>3,'name'=>'Hồng Ngự'),
							'4'=>array('id'=>4,'name'=>'Hồng Ngự'),
							'5'=>array('id'=>5,'name'=>'Lai Vung'),
							'6'=>array('id'=>6,'name'=>'Lấp Vò'),
							'7'=>array('id'=>7,'name'=>'Sa Đéc'),
							'8'=>array('id'=>8,'name'=>'Tân Hồng'),
							'9'=>array('id'=>9,'name'=>'Thanh Bình'),
							'10'=>array('id'=>10,'name'=>'Tháp Mười'),   ),
				'19'=>array('1'=>array('id'=>1,'name'=>'An Khê'),
							'2'=>array('id'=>2,'name'=>'Ayun Pa'),
							'3'=>array('id'=>3,'name'=>'Chư Păh'),
							'4'=>array('id'=>4,'name'=>'Chư Prông'),
							'5'=>array('id'=>5,'name'=>'Chư Pưh'),
							'6'=>array('id'=>6,'name'=>'Chư Sê'),
							'7'=>array('id'=>7,'name'=>'Đăk Đoa'),
							'8'=>array('id'=>8,'name'=>'Đăk Pơ'),
							'9'=>array('id'=>9,'name'=>'Đức Cơ'),
							'10'=>array('id'=>10,'name'=>'Huyện KBang'),
							'11'=>array('id'=>11,'name'=>'Ia Grai'),
							'12'=>array('id'=>12,'name'=>'Ia Pa'),
							'13'=>array('id'=>13,'name'=>'Kông Chro'),
							'14'=>array('id'=>14,'name'=>'Krông Pa'),
							'15'=>array('id'=>15,'name'=>'Mang Yang'),
							'16'=>array('id'=>16,'name'=>'Phú Thiện'),
							'17'=>array('id'=>17,'name'=>'Pleiku'),   ),
				'20'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Mê'),
							'2'=>array('id'=>2,'name'=>'Bắc Quang'),
							'3'=>array('id'=>3,'name'=>'Đồng Văn'),
							'4'=>array('id'=>4,'name'=>'Hà Giang'),
							'5'=>array('id'=>5,'name'=>'Hoàng Su Phì'),
							'6'=>array('id'=>6,'name'=>'Mèo Vạc'),
							'7'=>array('id'=>7,'name'=>'Quản Bạ'),
							'8'=>array('id'=>8,'name'=>'Quang Bình'),
							'9'=>array('id'=>9,'name'=>'Vị Xuyên'),
							'10'=>array('id'=>10,'name'=>'Xín Mần'),
							'11'=>array('id'=>11,'name'=>'Yên Minh'),   ),
				'21'=>array(  '1'=>array('id'=>1,'name'=>'Bình Lục'),
							'2'=>array('id'=>2,'name'=>'Duy Tiên'),
							'3'=>array('id'=>3,'name'=>'Kim Bảng'),
							'4'=>array('id'=>4,'name'=>'Lý Nhân'),
							'5'=>array('id'=>5,'name'=>'Phủ Lý'),
							'6'=>array('id'=>6,'name'=>'Thanh Liêm'),   ),
				'22'=>array(  '1'=>array('id'=>1,'name'=>'Cẩm Xuyên'),
							'2'=>array('id'=>2,'name'=>'Can Lộc'),
							'3'=>array('id'=>3,'name'=>'Đức Thọ'),
							'4'=>array('id'=>4,'name'=>'Hà Tĩnh'),
							'5'=>array('id'=>5,'name'=>'Hồng Lĩnh'),
							'6'=>array('id'=>6,'name'=>'Hương Khê'),
							'7'=>array('id'=>7,'name'=>'Hương Sơn'),
							'8'=>array('id'=>8,'name'=>'Kỳ Anh'),
							'9'=>array('id'=>9,'name'=>'Kỳ Anh'),
							'10'=>array('id'=>10,'name'=>'Lộc Hà'),
							'11'=>array('id'=>11,'name'=>'Nghi Xuân'),
							'12'=>array('id'=>12,'name'=>'Thạch Hà'),
							'13'=>array('id'=>13,'name'=>'Vũ Quang'),   ),
				'23'=>array(  '1'=>array('id'=>1,'name'=>'Bình Giang'),
							'2'=>array('id'=>2,'name'=>'Cẩm Giàng'),
							'3'=>array('id'=>3,'name'=>'Chí Linh'),
							'4'=>array('id'=>4,'name'=>'Gia Lộc'),
							'5'=>array('id'=>5,'name'=>'Hải Dương'),
							'6'=>array('id'=>6,'name'=>'Kim Thành'),
							'7'=>array('id'=>7,'name'=>'Kinh Môn'),
							'8'=>array('id'=>8,'name'=>'Nam Sách'),
							'9'=>array('id'=>9,'name'=>'Ninh Giang'),
							'10'=>array('id'=>10,'name'=>'Thanh Hà'),
							'11'=>array('id'=>11,'name'=>'Thanh Miện'),
							'12'=>array('id'=>12,'name'=>'Tứ Kỳ'),   ),
				'24'=>array(  '1'=>array('id'=>1,'name'=>'Châu Thành A'),
							'2'=>array('id'=>2,'name'=>'Long Mỹ'),
							'3'=>array('id'=>3,'name'=>'Long Mỹ'),
							'4'=>array('id'=>4,'name'=>'Ngã Bảy'),
							'5'=>array('id'=>5,'name'=>'Phụng Hiệp'),
							'6'=>array('id'=>6,'name'=>'Vị Thanh'),
							'7'=>array('id'=>7,'name'=>'Vị Thuỷ'),   ),
				'25'=>array(  '1'=>array('id'=>1,'name'=>'Cao Phong'),
							'2'=>array('id'=>2,'name'=>'Đà Bắc'),
							'3'=>array('id'=>3,'name'=>'Hòa Bình'),
							'4'=>array('id'=>4,'name'=>'Kim Bôi'),
							'5'=>array('id'=>5,'name'=>'Kỳ Sơn'),
							'6'=>array('id'=>6,'name'=>'Lạc Sơn'),
							'7'=>array('id'=>7,'name'=>'Lạc Thủy'),
							'8'=>array('id'=>8,'name'=>'Lương Sơn'),
							'9'=>array('id'=>9,'name'=>'Mai Châu'),
							'10'=>array('id'=>10,'name'=>'Tân Lạc'),
							'11'=>array('id'=>11,'name'=>'Yên Thủy'),   ),
				'26'=>array(  '1'=>array('id'=>1,'name'=>'Ân Thi'),
							'2'=>array('id'=>2,'name'=>'Hưng Yên'),
							'3'=>array('id'=>3,'name'=>'Khoái Châu'),
							'4'=>array('id'=>4,'name'=>'Kim Động'),
							'5'=>array('id'=>5,'name'=>'Mỹ Hào'),
							'6'=>array('id'=>6,'name'=>'Phù Cừ'),
							'7'=>array('id'=>7,'name'=>'Tiên Lữ'),
							'8'=>array('id'=>8,'name'=>'Văn Giang'),
							'9'=>array('id'=>9,'name'=>'Văn Lâm'),
							'10'=>array('id'=>10,'name'=>'Yên Mỹ'),   ),
				'27'=>array(  '1'=>array('id'=>1,'name'=>'Cam Lâm'),
							'2'=>array('id'=>2,'name'=>'Cam Ranh'),
							'3'=>array('id'=>3,'name'=>'Diên Khánh'),
							'4'=>array('id'=>4,'name'=>'Khánh Sơn'),
							'5'=>array('id'=>5,'name'=>'Khánh Vĩnh'),
							'6'=>array('id'=>6,'name'=>'Nha Trang'),
							'7'=>array('id'=>7,'name'=>'Ninh Hòa'),
							'8'=>array('id'=>8,'name'=>'Trường Sa'),
							'9'=>array('id'=>9,'name'=>'Vạn Ninh'),   ),
				'28'=>array(  '1'=>array('id'=>1,'name'=>'An Biên'),
							'2'=>array('id'=>2,'name'=>'An Minh'),
							'3'=>array('id'=>3,'name'=>'Giang Thành'),
							'4'=>array('id'=>4,'name'=>'Giồng Riềng'),
							'5'=>array('id'=>5,'name'=>'Gò Quao'),
							'6'=>array('id'=>6,'name'=>'Hà Tiên'),
							'7'=>array('id'=>7,'name'=>'Hòn Đất'),
							'8'=>array('id'=>8,'name'=>'Kiên Hải'),
							'9'=>array('id'=>9,'name'=>'Kiên Lương'),
							'10'=>array('id'=>10,'name'=>'Phú Quốc'),
							'11'=>array('id'=>11,'name'=>'Rạch Giá'),
							'12'=>array('id'=>12,'name'=>'Tân Hiệp'),
							'13'=>array('id'=>13,'name'=>'U Minh Thượng'),
							'14'=>array('id'=>14,'name'=>'Vĩnh Thuận'),   ),
				'29'=>array(  '1'=>array('id'=>1,'name'=>'Đắk Glei'),
							'2'=>array('id'=>2,'name'=>'Đắk Hà'),
							'3'=>array('id'=>3,'name'=>'Đắk Tô'),
							'4'=>array('id'=>4,'name'=>'H Drai'),
							'5'=>array('id'=>5,'name'=>'Kon Plông'),
							'6'=>array('id'=>6,'name'=>'Kon Rẫy'),
							'7'=>array('id'=>7,'name'=>'Kon Tum'),
							'8'=>array('id'=>8,'name'=>'Mơ Rông'),
							'9'=>array('id'=>9,'name'=>'Ngọc Hồi'),
							'10'=>array('id'=>10,'name'=>'Sa Thầy'),   ),
				'30'=>array(  '1'=>array('id'=>1,'name'=>'Lai Châu'),
							'2'=>array('id'=>2,'name'=>'Mường Tè'),
							'3'=>array('id'=>3,'name'=>'Nậm Nhùn'),
							'4'=>array('id'=>4,'name'=>'Phong Thổ'),
							'5'=>array('id'=>5,'name'=>'Sìn Hồ'),
							'6'=>array('id'=>6,'name'=>'Tam Đường'),
							'7'=>array('id'=>7,'name'=>'Tân Uyên'),
							'8'=>array('id'=>8,'name'=>'Than Uyên'),   ),
				'31'=>array(  '1'=>array('id'=>1,'name'=>'Bảo Lộc'),
							'2'=>array('id'=>2,'name'=>'Cát Tiên'),
							'3'=>array('id'=>3,'name'=>'Đạ Huoai'),
							'4'=>array('id'=>4,'name'=>'Đà Lạt'),
							'5'=>array('id'=>5,'name'=>'Đạ Tẻh'),
							'6'=>array('id'=>6,'name'=>'Đam Rông'),
							'7'=>array('id'=>7,'name'=>'Di Linh'),
							'8'=>array('id'=>8,'name'=>'Đơn Dương'),
							'9'=>array('id'=>9,'name'=>'Đức Trọng'),
							'10'=>array('id'=>10,'name'=>'Lạc Dương'),
							'11'=>array('id'=>11,'name'=>'Lâm Hà'),   ),
				'32'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Sơn'),
							'2'=>array('id'=>2,'name'=>'Bình Gia'),
							'3'=>array('id'=>3,'name'=>'Cao Lộc'),
							'4'=>array('id'=>4,'name'=>'Chi Lăng'),
							'5'=>array('id'=>5,'name'=>'Đình Lập'),
							'6'=>array('id'=>6,'name'=>'Hữu Lũng'),
							'7'=>array('id'=>7,'name'=>'Lạng Sơn'),
							'8'=>array('id'=>8,'name'=>'Lộc Bình'),
							'9'=>array('id'=>9,'name'=>'Tràng Định'),
							'10'=>array('id'=>10,'name'=>'Văn Lãng'),
							'11'=>array('id'=>11,'name'=>'Văn Quan'),   ),
				'33'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Hà'),
							'2'=>array('id'=>2,'name'=>'Bảo Thắng'),
							'3'=>array('id'=>3,'name'=>'Bảo Yên'),
							'4'=>array('id'=>4,'name'=>'Bát Xát'),
							'5'=>array('id'=>5,'name'=>'Lào Cai'),
							'6'=>array('id'=>6,'name'=>'Ma Cai'),
							'7'=>array('id'=>7,'name'=>'Mường Khương'),
							'8'=>array('id'=>8,'name'=>'Sa Pa'),
							'9'=>array('id'=>9,'name'=>'Văn Bàn'),   ),
				'34'=>array(  '1'=>array('id'=>1,'name'=>'Bến Lức'),
							'2'=>array('id'=>2,'name'=>'Cần Đước'),
							'3'=>array('id'=>3,'name'=>'Cần Giuộc'),
							'4'=>array('id'=>4,'name'=>'Đức Hòa'),
							'5'=>array('id'=>5,'name'=>'Đức Huệ'),
							'6'=>array('id'=>6,'name'=>'Kiến Tường'),
							'7'=>array('id'=>7,'name'=>'Mộc Hóa'),
							'8'=>array('id'=>8,'name'=>'Tân An'),
							'9'=>array('id'=>9,'name'=>'Tân Hưng'),
							'10'=>array('id'=>10,'name'=>'Tân Thạnh'),
							'11'=>array('id'=>11,'name'=>'Tân Trụ'),
							'12'=>array('id'=>12,'name'=>'Thạnh Hóa'),
							'13'=>array('id'=>13,'name'=>'Thủ Thừa'),
							'14'=>array('id'=>14,'name'=>'Vĩnh Hưng'),   ),
				'35'=>array(  '1'=>array('id'=>1,'name'=>'Giao Thủy'),
							'2'=>array('id'=>2,'name'=>'Hải Hậu'),
							'3'=>array('id'=>3,'name'=>'Mỹ Lộc'),
							'4'=>array('id'=>4,'name'=>'Nam Định'),
							'5'=>array('id'=>5,'name'=>'Nam Trực'),
							'6'=>array('id'=>6,'name'=>'Nghĩa Hưng'),
							'7'=>array('id'=>7,'name'=>'Trực Ninh'),
							'8'=>array('id'=>8,'name'=>'Vụ Bản'),
							'9'=>array('id'=>9,'name'=>'Xuân Trường'),
							'10'=>array('id'=>10,'name'=>'Ý Yên'),   ),
				'36'=>array(  '1'=>array('id'=>1,'name'=>'Anh Sơn'),
							'2'=>array('id'=>2,'name'=>'Con Cuông'),
							'3'=>array('id'=>3,'name'=>'Cửa Lò'),
							'4'=>array('id'=>4,'name'=>'Diễn Châu'),
							'5'=>array('id'=>5,'name'=>'Đô Lương'),
							'6'=>array('id'=>6,'name'=>'Hoàng Mai'),
							'7'=>array('id'=>7,'name'=>'Hưng Nguyên'),
							'8'=>array('id'=>8,'name'=>'Nam Đàn'),
							'9'=>array('id'=>9,'name'=>'Nghi Lộc'),
							'10'=>array('id'=>10,'name'=>'Nghĩa Đàn'),
							'11'=>array('id'=>11,'name'=>'phố Vinh'),
							'12'=>array('id'=>12,'name'=>'Quế Phong'),
							'13'=>array('id'=>13,'name'=>'Quỳ Châu'),
							'14'=>array('id'=>14,'name'=>'Quỳ Hợp'),
							'15'=>array('id'=>15,'name'=>'Quỳnh Lưu'),
							'16'=>array('id'=>16,'name'=>'Tân Kỳ'),
							'17'=>array('id'=>17,'name'=>'Thái Hoà'),
							'18'=>array('id'=>18,'name'=>'Thanh Chương'),
							'19'=>array('id'=>19,'name'=>'Tương Dương'),
							'20'=>array('id'=>20,'name'=>'Yên Thành'),   ),
				'37'=>array(  '1'=>array('id'=>1,'name'=>'Gia Viễn'),
							'2'=>array('id'=>2,'name'=>'Hoa Lư'),
							'3'=>array('id'=>3,'name'=>'Kim Sơn'),
							'4'=>array('id'=>4,'name'=>'Nho Quan'),
							'5'=>array('id'=>5,'name'=>'Ninh Bình'),
							'6'=>array('id'=>6,'name'=>'Tam Điệp'),
							'7'=>array('id'=>7,'name'=>'Yên Khánh'),
							'8'=>array('id'=>8,'name'=>'Yên Mô'),   ),
				'38'=>array(  '1'=>array('id'=>1,'name'=>'Bác Ái'),
							'2'=>array('id'=>2,'name'=>'Ninh Hải'),
							'3'=>array('id'=>3,'name'=>'Ninh Phước'),
							'4'=>array('id'=>4,'name'=>'Ninh Sơn'),
							'5'=>array('id'=>5,'name'=>'Phan Rang-Tháp Chàm'),
							'6'=>array('id'=>6,'name'=>'Thuận Bắc'),
							'7'=>array('id'=>7,'name'=>'Thuận Nam'),   ),
				'39'=>array(  '1'=>array('id'=>1,'name'=>'Cẩm Khê'),
							'2'=>array('id'=>2,'name'=>'Đoan Hùng'),
							'3'=>array('id'=>3,'name'=>'Hạ Hoà'),
							'4'=>array('id'=>4,'name'=>'Lâm Thao'),
							'5'=>array('id'=>5,'name'=>'Phù Ninh'),
							'6'=>array('id'=>6,'name'=>'Phú Thọ'),
							'7'=>array('id'=>7,'name'=>'Tam Nông'),
							'8'=>array('id'=>8,'name'=>'Tân Sơn'),
							'9'=>array('id'=>9,'name'=>'Thanh Ba'),
							'10'=>array('id'=>10,'name'=>'Thanh Sơn'),
							'11'=>array('id'=>11,'name'=>'Thanh Thuỷ'),
							'12'=>array('id'=>12,'name'=>'Việt Trì'),
							'13'=>array('id'=>13,'name'=>'Yên Lập'),   ),
				'40'=>array(  '1'=>array('id'=>1,'name'=>'Ba Đồn'),
							'2'=>array('id'=>2,'name'=>'Bố Trạch'),
							'3'=>array('id'=>3,'name'=>'Đồng Hới'),
							'4'=>array('id'=>4,'name'=>'Lệ Thủy'),
							'5'=>array('id'=>5,'name'=>'Minh Hóa'),
							'6'=>array('id'=>6,'name'=>'Quảng Ninh'),
							'7'=>array('id'=>7,'name'=>'Quảng Trạch'),
							'8'=>array('id'=>8,'name'=>'Tuyên Hóa'),   ),
				'41'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Trà My'),
							'2'=>array('id'=>2,'name'=>'Đại Lộc'),
							'3'=>array('id'=>3,'name'=>'Điện Bàn'),
							'4'=>array('id'=>4,'name'=>'Đông Giang'),
							'5'=>array('id'=>5,'name'=>'Duy Xuyên'),
							'6'=>array('id'=>6,'name'=>'Hiệp Đức'),
							'7'=>array('id'=>7,'name'=>'Hội An'),
							'8'=>array('id'=>8,'name'=>'Nam Giang'),
							'9'=>array('id'=>9,'name'=>'Nam Trà My'),
							'10'=>array('id'=>10,'name'=>'Nông Sơn'),
							'11'=>array('id'=>11,'name'=>'Núi Thành'),
							'12'=>array('id'=>12,'name'=>'Phú Ninh'),
							'13'=>array('id'=>13,'name'=>'Phước Sơn'),
							'14'=>array('id'=>14,'name'=>'Quế Sơn'),
							'15'=>array('id'=>15,'name'=>'Tam Kỳ'),
							'16'=>array('id'=>16,'name'=>'Tây Giang'),
							'17'=>array('id'=>17,'name'=>'Thăng Bình'),
							'18'=>array('id'=>18,'name'=>'Tiên Phước'),   ),
				'42'=>array(  '1'=>array('id'=>1,'name'=>'Ba Tơ'),
							'2'=>array('id'=>2,'name'=>'Bình Sơn'),
							'3'=>array('id'=>3,'name'=>'Đức Phổ'),
							'4'=>array('id'=>4,'name'=>'Lý Sơn'),
							'5'=>array('id'=>5,'name'=>'Minh Long'),
							'6'=>array('id'=>6,'name'=>'Mộ Đức'),
							'7'=>array('id'=>7,'name'=>'Nghĩa Hành'),
							'8'=>array('id'=>8,'name'=>'Quảng Ngãi'),
							'9'=>array('id'=>9,'name'=>'Sơn Hà'),
							'10'=>array('id'=>10,'name'=>'Sơn Tây'),
							'11'=>array('id'=>11,'name'=>'Sơn Tịnh'),
							'12'=>array('id'=>12,'name'=>'Tây Trà'),
							'13'=>array('id'=>13,'name'=>'Trà Bồng'),
							'14'=>array('id'=>14,'name'=>'Tư Nghĩa'),   ),
				'43'=>array(  '1'=>array('id'=>1,'name'=>'Ba Chẽ'),
							'2'=>array('id'=>2,'name'=>'Bình Liêu'),
							'3'=>array('id'=>3,'name'=>'Cẩm Phả'),
							'4'=>array('id'=>4,'name'=>'Cô Tô'),
							'5'=>array('id'=>5,'name'=>'Đầm Hà'),
							'6'=>array('id'=>6,'name'=>'Đông Triều'),
							'7'=>array('id'=>7,'name'=>'Hạ Long'),
							'8'=>array('id'=>8,'name'=>'Hải Hà'),
							'9'=>array('id'=>9,'name'=>'Hoành Bồ'),
							'10'=>array('id'=>10,'name'=>'Móng Cái'),
							'11'=>array('id'=>11,'name'=>'Quảng Yên'),
							'12'=>array('id'=>12,'name'=>'Tiên Yên'),
							'13'=>array('id'=>13,'name'=>'Uông Bí'),
							'14'=>array('id'=>14,'name'=>'Vân Đồn'),   ),
				'44'=>array(  '1'=>array('id'=>1,'name'=>'Cam Lộ'),
							'2'=>array('id'=>2,'name'=>'Đa Krông'),
							'3'=>array('id'=>3,'name'=>'Đông Hà'),
							'4'=>array('id'=>4,'name'=>'Gio Linh'),
							'5'=>array('id'=>5,'name'=>'Hải Lăng'),
							'6'=>array('id'=>6,'name'=>'Hướng Hóa'),
							'7'=>array('id'=>7,'name'=>'Quảng Trị'),
							'8'=>array('id'=>8,'name'=>'Triệu Phong'),
							'9'=>array('id'=>9,'name'=>'Vĩnh Linh'),   ),
				'45'=>array(  '1'=>array('id'=>1,'name'=>'Cù Lao Dung'),
							'2'=>array('id'=>2,'name'=>'Kế Sách'),
							'3'=>array('id'=>3,'name'=>'Long Phú'),
							'4'=>array('id'=>4,'name'=>'Mỹ Tú'),
							'5'=>array('id'=>5,'name'=>'Mỹ Xuyên'),
							'6'=>array('id'=>6,'name'=>'Ngã Năm'),
							'7'=>array('id'=>7,'name'=>'Sóc Trăng'),
							'8'=>array('id'=>8,'name'=>'Thạnh Trị'),
							'9'=>array('id'=>9,'name'=>'Trần Đề'),
							'10'=>array('id'=>10,'name'=>'Vĩnh Châu'),   ),
				'46'=>array(  '1'=>array('id'=>1,'name'=>'Bắc Yên'),
							'2'=>array('id'=>2,'name'=>'Mai Sơn'),
							'3'=>array('id'=>3,'name'=>'Mộc Châu'),
							'4'=>array('id'=>4,'name'=>'Mường La'),
							'5'=>array('id'=>5,'name'=>'Phù Yên'),
							'6'=>array('id'=>6,'name'=>'Quỳnh Nhai'),
							'7'=>array('id'=>7,'name'=>'Sơn La'),
							'8'=>array('id'=>8,'name'=>'Sông Mã'),
							'9'=>array('id'=>9,'name'=>'Sốp Cộp'),
							'10'=>array('id'=>10,'name'=>'Thuận Châu'),
							'11'=>array('id'=>11,'name'=>'Vân Hồ'),
							'12'=>array('id'=>12,'name'=>'Yên Châu'),   ),
				'47'=>array(  '1'=>array('id'=>1,'name'=>'Bến Cầu'),
							'2'=>array('id'=>2,'name'=>'Châu Thành'),
							'3'=>array('id'=>3,'name'=>'Dương Minh Châu'),
							'4'=>array('id'=>4,'name'=>'Gò Dầu'),
							'5'=>array('id'=>5,'name'=>'Hòa Thành'),
							'6'=>array('id'=>6,'name'=>'Tân Biên'),
							'7'=>array('id'=>7,'name'=>'Tân Châu'),
							'8'=>array('id'=>8,'name'=>'Tây Ninh'),
							'9'=>array('id'=>9,'name'=>'Trảng Bàng'),   ),
				'48'=>array(  '1'=>array('id'=>1,'name'=>'Đông Hưng'),
							'2'=>array('id'=>2,'name'=>'Hưng Hà'),
							'3'=>array('id'=>3,'name'=>'Kiến Xương'),
							'4'=>array('id'=>4,'name'=>'Quỳnh Phụ'),
							'5'=>array('id'=>5,'name'=>'Thái Bình'),
							'6'=>array('id'=>6,'name'=>'Thái Thụy'),
							'7'=>array('id'=>7,'name'=>'Tiền Hải'),
							'8'=>array('id'=>8,'name'=>'Vũ Thư'),   ),
				'49'=>array(  '1'=>array('id'=>1,'name'=>'Đại Từ'),
							'2'=>array('id'=>2,'name'=>'Định Hóa'),
							'3'=>array('id'=>3,'name'=>'Đồng Hỷ'),
							'4'=>array('id'=>4,'name'=>'Phổ Yên'),
							'5'=>array('id'=>5,'name'=>'Phú Bình'),
							'6'=>array('id'=>6,'name'=>'Phú Lương'),
							'7'=>array('id'=>7,'name'=>'Sông Công'),
							'8'=>array('id'=>8,'name'=>'Thái Nguyên'),
							'9'=>array('id'=>9,'name'=>'Võ Nhai'),   ),
				'50'=>array(  '1'=>array('id'=>1,'name'=>'Bá Thước'),
							'2'=>array('id'=>2,'name'=>'Bỉm Sơn'),
							'3'=>array('id'=>3,'name'=>'Cẩm Thủy'),
							'4'=>array('id'=>4,'name'=>'Đông Sơn'),
							'5'=>array('id'=>5,'name'=>'Hà Trung'),
							'6'=>array('id'=>6,'name'=>'Hậu Lộc'),
							'7'=>array('id'=>7,'name'=>'Hoằng Hóa'),
							'8'=>array('id'=>8,'name'=>'Lang Chánh'),
							'9'=>array('id'=>9,'name'=>'Mường Lát'),
							'10'=>array('id'=>10,'name'=>'Nga Sơn'),
							'11'=>array('id'=>11,'name'=>'Ngọc Lặc'),
							'12'=>array('id'=>12,'name'=>'Như Thanh'),
							'13'=>array('id'=>13,'name'=>'Như Xuân'),
							'14'=>array('id'=>14,'name'=>'Nông Cống'),
							'15'=>array('id'=>15,'name'=>'Quan Hóa'),
							'16'=>array('id'=>16,'name'=>'Quan Sơn'),
							'17'=>array('id'=>17,'name'=>'Quảng Xương'),
							'18'=>array('id'=>18,'name'=>'Sầm Sơn'),
							'19'=>array('id'=>19,'name'=>'Thạch Thành'),
							'20'=>array('id'=>20,'name'=>'Thanh Hóa'),
							'21'=>array('id'=>21,'name'=>'Thiệu Hóa'),
							'22'=>array('id'=>22,'name'=>'Thọ Xuân'),
							'23'=>array('id'=>23,'name'=>'Thường Xuân'),
							'24'=>array('id'=>24,'name'=>'Tĩnh Gia'),
							'25'=>array('id'=>25,'name'=>'Triệu Sơn'),
							'26'=>array('id'=>26,'name'=>'Vĩnh Lộc'),
							'27'=>array('id'=>27,'name'=>'Yên Định'),   ),
				'51'=>array(  '1'=>array('id'=>1,'name'=>'A Lưới'),
							'2'=>array('id'=>2,'name'=>'Hương Thủy'),
							'3'=>array('id'=>3,'name'=>'Hương Trà'),
							'4'=>array('id'=>4,'name'=>'Nam Đông'),
							'5'=>array('id'=>5,'name'=>'phố Huế'),
							'6'=>array('id'=>6,'name'=>'Phong Điền'),
							'7'=>array('id'=>7,'name'=>'Phú Lộc'),
							'8'=>array('id'=>8,'name'=>'Phú Vang'),
							'9'=>array('id'=>9,'name'=>'Quảng Điền'),   ),
				'52'=>array(  '1'=>array('id'=>1,'name'=>'Cái Bè'),
							'2'=>array('id'=>2,'name'=>'Cai Lậy'),
							'3'=>array('id'=>3,'name'=>'Cai Lậy'),
							'4'=>array('id'=>4,'name'=>'Chợ Gạo'),
							'5'=>array('id'=>5,'name'=>'Gò Công'),
							'6'=>array('id'=>6,'name'=>'Gò Công Đông'),
							'7'=>array('id'=>7,'name'=>'Gò Công Tây'),
							'8'=>array('id'=>8,'name'=>'Mỹ Tho'),
							'9'=>array('id'=>9,'name'=>'Tân Phú Đông'),
							'10'=>array('id'=>10,'name'=>'Tân Phước'),   ),
				'53'=>array(  '1'=>array('id'=>1,'name'=>'Càng Long'),
							'2'=>array('id'=>2,'name'=>'Cầu Kè'),
							'3'=>array('id'=>3,'name'=>'Cầu Ngang'),
							'4'=>array('id'=>4,'name'=>'Duyên Hải'),
							'5'=>array('id'=>5,'name'=>'Duyên Hải'),
							'6'=>array('id'=>6,'name'=>'Tiểu Cần'),
							'7'=>array('id'=>7,'name'=>'Trà Cú'),
							'8'=>array('id'=>8,'name'=>'Trà Vinh'),   ),
				'54'=>array(  '1'=>array('id'=>1,'name'=>'Chiêm Hóa'),
							'2'=>array('id'=>2,'name'=>'Hàm Yên'),
							'3'=>array('id'=>3,'name'=>'Lâm Bình'),
							'4'=>array('id'=>4,'name'=>'Nà Hang'),
							'5'=>array('id'=>5,'name'=>'Sơn Dương'),
							'6'=>array('id'=>6,'name'=>'Tuyên Quang'),
							'7'=>array('id'=>7,'name'=>'Yên Sơn'),   ),
				'55'=>array(  '1'=>array('id'=>1,'name'=>'Bình Minh'),
							'2'=>array('id'=>2,'name'=>'Bình Tân'),
							'3'=>array('id'=>3,'name'=>'Long Hồ'),
							'4'=>array('id'=>4,'name'=>'Mang Thít'),
							'5'=>array('id'=>5,'name'=>'Tam Bình'),
							'6'=>array('id'=>6,'name'=>'Trà Ôn'),
							'7'=>array('id'=>7,'name'=>'Vĩnh Long'),
							'8'=>array('id'=>8,'name'=>'Vũng Liêm'),   ),
				'56'=>array(  '1'=>array('id'=>1,'name'=>'Bình Xuyên'),
							'2'=>array('id'=>2,'name'=>'Lập Thạch'),
							'3'=>array('id'=>3,'name'=>'Phúc Yên'),
							'4'=>array('id'=>4,'name'=>'Sông Lô'),
							'5'=>array('id'=>5,'name'=>'Tam Đảo'),
							'6'=>array('id'=>6,'name'=>'Tam Dương'),
							'7'=>array('id'=>7,'name'=>'Vĩnh Tường'),
							'8'=>array('id'=>8,'name'=>'Vĩnh Yên'),
							'9'=>array('id'=>9,'name'=>'Yên Lạc'),   ),
				'57'=>array(  '1'=>array('id'=>1,'name'=>'Lục Yên'),
							'2'=>array('id'=>2,'name'=>'Mù Căng Chải'),
							'3'=>array('id'=>3,'name'=>'Nghĩa Lộ'),
							'4'=>array('id'=>4,'name'=>'Trạm Tấu'),
							'5'=>array('id'=>5,'name'=>'Trấn Yên'),
							'6'=>array('id'=>6,'name'=>'Văn Chấn'),
							'7'=>array('id'=>7,'name'=>'Văn Yên'),
							'8'=>array('id'=>8,'name'=>'Yên Bái'),
							'9'=>array('id'=>9,'name'=>'Yên Bình'),   ),
				'58'=>array(  '1'=>array('id'=>1,'name'=>'Đông Hòa'),
							'2'=>array('id'=>2,'name'=>'Đồng Xuân'),
							'3'=>array('id'=>3,'name'=>'Phú Hoà'),
							'4'=>array('id'=>4,'name'=>'Sơn Hòa'),
							'5'=>array('id'=>5,'name'=>'Sông Cầu'),
							'6'=>array('id'=>6,'name'=>'Sông Hinh'),
							'7'=>array('id'=>7,'name'=>'Tây Hoà'),
							'8'=>array('id'=>8,'name'=>'Tuy An'),
							'9'=>array('id'=>9,'name'=>'Tuy Hoà'),   ),
				'59'=>array(  '1'=>array('id'=>1,'name'=>'Bình Thuỷ'),
							'2'=>array('id'=>2,'name'=>'Cái Răng'),
							'3'=>array('id'=>3,'name'=>'Cờ Đỏ'),
							'4'=>array('id'=>4,'name'=>'Ninh Kiều'),
							'5'=>array('id'=>5,'name'=>'Ô Môn'),
							'6'=>array('id'=>6,'name'=>'Thới Lai'),
							'7'=>array('id'=>7,'name'=>'Thốt Nốt'),   ),
				'60'=>array(  '1'=>array('id'=>1,'name'=>'Cẩm Lệ'),
							'2'=>array('id'=>2,'name'=>'Hải Châu'),
							'3'=>array('id'=>3,'name'=>'Hòa Vang'),
							'4'=>array('id'=>4,'name'=>'Liên Chiểu'),
							'5'=>array('id'=>5,'name'=>'Ngũ Hành Sơn'),
							'6'=>array('id'=>6,'name'=>'Sơn Trà'),
							'7'=>array('id'=>7,'name'=>'Thanh Khê'),   ),
				'61'=>array(  '1'=>array('id'=>1,'name'=>'An Dương'),
							'2'=>array('id'=>2,'name'=>'An Lão'),
							'3'=>array('id'=>3,'name'=>'Cát Hải'),
							'4'=>array('id'=>4,'name'=>'Đồ Sơn'),
							'5'=>array('id'=>5,'name'=>'Dương Kinh'),
							'6'=>array('id'=>6,'name'=>'Hải An'),
							'7'=>array('id'=>7,'name'=>'Hồng Bàng'),
							'8'=>array('id'=>8,'name'=>'Kiến An'),
							'9'=>array('id'=>9,'name'=>'Kiến Thuỵ'),
							'10'=>array('id'=>10,'name'=>'Lê Chân'),
							'11'=>array('id'=>11,'name'=>'Ngô Quyền'),
							'12'=>array('id'=>12,'name'=>'Thuỷ Nguyên'),
							'13'=>array('id'=>13,'name'=>'Tiên Lãng'),
							'14'=>array('id'=>14,'name'=>'Vĩnh Bảo'),   ),
				'62'=>array(  '1'=>array('id'=>1,'name'=>'Ba Đình'),
							'2'=>array('id'=>2,'name'=>'Ba Vì'),
							'3'=>array('id'=>3,'name'=>'Bắc Từ Liêm'),
							'4'=>array('id'=>4,'name'=>'Cầu Giấy'),
							'5'=>array('id'=>5,'name'=>'Chương Mỹ'),
							'6'=>array('id'=>6,'name'=>'Đan Phượng'),
							'7'=>array('id'=>7,'name'=>'Đông Anh'),
							'8'=>array('id'=>8,'name'=>'Đống Đa'),
							'9'=>array('id'=>9,'name'=>'Gia Lâm'),
							'10'=>array('id'=>10,'name'=>'Hà Đông'),
							'11'=>array('id'=>11,'name'=>'Hai Bà Trưng'),
							'12'=>array('id'=>12,'name'=>'Hoài Đức'),
							'13'=>array('id'=>13,'name'=>'Hoàn Kiếm'),
							'14'=>array('id'=>14,'name'=>'Hoàng Mai'),
							'15'=>array('id'=>15,'name'=>'Long Biên'),
							'16'=>array('id'=>16,'name'=>'Mê Linh'),
							'17'=>array('id'=>17,'name'=>'Mỹ Đức'),
							'18'=>array('id'=>18,'name'=>'Nam Từ Liêm'),
							'19'=>array('id'=>19,'name'=>'Phú Xuyên'),
							'20'=>array('id'=>20,'name'=>'Phúc Thọ'),
							'21'=>array('id'=>21,'name'=>'Quốc Oai'),
							'22'=>array('id'=>22,'name'=>'Sóc Sơn'),
							'23'=>array('id'=>23,'name'=>'Sơn Tây'),
							'24'=>array('id'=>24,'name'=>'Tây Hồ'),
							'25'=>array('id'=>25,'name'=>'Thạch Thất'),
							'26'=>array('id'=>26,'name'=>'Thanh Oai'),
							'27'=>array('id'=>27,'name'=>'Thanh Trì'),
							'28'=>array('id'=>28,'name'=>'Thanh Xuân'),
							'29'=>array('id'=>29,'name'=>'Thường Tín'),
							'30'=>array('id'=>30,'name'=>'Ứng Hòa'),   ),
				'63'=>array(  '1'=>array('id'=>1,'name'=>'Bình Chánh'),
							'2'=>array('id'=>2,'name'=>'Bình Tân'),
							'3'=>array('id'=>3,'name'=>'Bình Thạnh'),
							'4'=>array('id'=>4,'name'=>'Cần Giờ'),
							'5'=>array('id'=>5,'name'=>'Củ Chi'),
							'6'=>array('id'=>6,'name'=>'Gò Vấp'),
							'7'=>array('id'=>7,'name'=>'Hóc Môn'),
							'8'=>array('id'=>8,'name'=>'Nhà Bè'),
							'9'=>array('id'=>9,'name'=>'Phú Nhuận'),
							'10'=>array('id'=>10,'name'=>'Quận 1'),
							'11'=>array('id'=>11,'name'=>'Quận 10'),
							'12'=>array('id'=>12,'name'=>'Quận 11'),
							'13'=>array('id'=>13,'name'=>'Quận 12'),
							'14'=>array('id'=>14,'name'=>'Quận 2'),
							'15'=>array('id'=>15,'name'=>'Quận 3'),
							'16'=>array('id'=>16,'name'=>'Quận 4'),
							'17'=>array('id'=>17,'name'=>'Quận 5'),
							'18'=>array('id'=>18,'name'=>'Quận 6'),
							'19'=>array('id'=>19,'name'=>'Quận 7'),
							'20'=>array('id'=>20,'name'=>'Quận 8'),
							'21'=>array('id'=>21,'name'=>'Quận 9'),
							'22'=>array('id'=>22,'name'=>'Tân Bình'),
							'23'=>array('id'=>23,'name'=>'Tân Phú'),
							'24'=>array('id'=>24,'name'=>'Thủ Đức'),  
                            ),      
			);
	
	if(!empty($idCity)){
		return $list[$idCity];
	}else{
		return $list;
	}
}

function getGUID()
{
    if (function_exists('com_create_guid')){
        return com_create_guid();
    }else{
        mt_srand((double)microtime()*10000);//optional for php 4.2.0 and up.
        $charid = strtoupper(md5(uniqid(rand(), true)));
        $hyphen = chr(45);// "-"
        $uuid = chr(123)// "{"
            .substr($charid, 0, 8).$hyphen
            .substr($charid, 8, 4).$hyphen
            .substr($charid,12, 4).$hyphen
            .substr($charid,16, 4).$hyphen
            .substr($charid,20,12)
            .chr(125);// "}"
        return $uuid;
    }
}

function getSignatureEmail()
{
	return '<p><strong>NetLoading</strong> là ứng dụng kết nối vận tải hàng hóa liên tỉnh thông minh đầu tiên tại Việt Nam, là sản phẩm trí óc và tâm huyết của đội ngũ sáng lập trẻ tuổi, nhiều hoài bão. Chúng tôi tự hào mang đến những công nghệ ưu việt nhất cho người dùng quan tâm đến lĩnh vực vận tải.</p>

			<p style="text-align:center"><span style="font-size:26px"><strong><span style="color:#008acb">HOTLINE: 0966671880</span></strong></span></p>

			<p>Website: <a href="http://www.netloading.com.vn">www.netloading.com.vn</a></p>

			<p>Email: netloading.co@gmail.com</p>

			<p>Địa chỉ: Số 22, ngách 31, ngõ 383, phố Phúc Tân, Phường Phúc Tân, Quận Hoàn Kiếm, Hà Nội</p>';
}

function sendMessageNotifi($data,$target){
	/*  
	Parameter Example
		$data = array('post_id'=>'12345','post_title'=>'A Blog post');
		$target = 'single tocken id or topic name';
		or
		$target = array('token1','token2','...'); // up to 1000 in one request
	*/
	//FCM api URL
	$url = 'https://fcm.googleapis.com/fcm/send';
	//api_key available in Firebase Console -> Project Settings -> CLOUD MESSAGING -> Server key
	$server_key = 'AAAAPuSVEww:APA91bG2GgHVgWrGLsOL3lwC3uGxkO9jY_iT7-A8RGVtEjCnLs0m1Hgnojfo-FCqtrb5oXELBdsB3e3dELWeIC-WTdqAhyhvRKYKeFamIsXM8Qz5SMszfPNKAKSc8uh9l6iWI_1DlBSvPzCzzfjxiVRKXpx_q3WFQw';
				
	$fields = array();
	$fields['data'] = $data;
	if(is_array($target)){
		$fields['registration_ids'] = $target;
	}else{
		$fields['to'] = $target;
	}
	//header with content_type api key
	$headers = array(
		'Content-Type:application/json',
	  'Authorization:key='.$server_key
	);
				
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
	$result = curl_exec($ch);
	if ($result === FALSE) {
		//die('FCM Send Error: ' . curl_error($ch));
	}
	curl_close($ch);
	//return $result;
}

?>